[loggers]
keys=root,ina_ground_control

[handlers]
keys=consoleHandler

[formatters]
keys=otel_format

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_ina_ground_control]
level=DEBUG
handlers=consoleHandler
qualname=ina_ground_control
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=otel_format
args=(sys.stdout,)

[formatter_otel_format]
format={"timestamp": "%(asctime)s", "severity": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}
