[global]
index = https://repo.sas.ina/repository/pypi
index-url = https://repo.sas.ina/repository/pypi/simple
extra-index-url = https://repo.sas.ina/repository/pypi-snapshots/simple
                  https://repo.sas.ina/repository/pypi-releases/simple
                  https://nexus.rech.ina.fr/repository/Pypy-hosted/simple
trusted-host = repo.sas.ina
               nexus.rech.ina.fr
