sonar.sources=ina_ground_control
sonar.test = tests
sonar.exclusions =**/alembic/**,**/tests/**,**/__pycache__/**,**/venv/**,**/.venv/**,**/routers/**,**/constants/**,**/main.py,**/schemas/**,**/config.py
sonar.coverage.exclusions =**/alembic/**,**/tests/**,**/__pycache__/**,**/venv/**,**/.venv/**,**/routers/**,**/constants/**,**/main.py,**/schemas/**,**/config.py
