[tox]
envlist = python3
isolated_build=True

[testenv]
deps =
    pylint
    pytest
    pytest-cov
    pytest-mock
    jsonpath-ng==1.7.0
setenv =
    HOME = /tmp
    NO_AUTH = True

commands =
    pytest --junitxml=junit_{envname}.xml --cov=ina_ground_control --cov-report=html --cov-report term-missing
    pylint ina_ground_control/ --ignore=alembic
