[tox]
envlist = py311
isolated_build=True

[testenv]
deps =
    pylint
    flake8
    pytest
    pytest-cov
    pytest-mock
setenv =
    HOME = /tmp

commands =
;     pytest --junitxml=junit_{envname}.xml --cov=ina_ground_control --cov-report=html
    pylint ina_ground_control/
    flake8
