[tox]
envlist = py311
isolated_build=True

[testenv]
deps =
    pylint
    flake8
    pytest
    pytest-cov
    pytest-mock
setenv =
    HOME = /tmp

commands =
;     pylint src/
;     flake8
    pytest -vv --cov=src --cov-report=html

