"""new model correction

Revision ID: 69afcacbe02f
Revises: be50ab73e53e
Create Date: 2024-07-12 16:01:36.957979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69afcacbe02f'
down_revision: Union[str, None] = 'be50ab73e53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_project',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'project_id')
    )
    op.create_table('tag_project',
    sa.Column('tag_key', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag_key'], ['tag.key'], ),
    sa.PrimaryKeyConstraint('tag_key', 'project_id')
    )
    op.drop_column('step', 'status')
    op.add_column('tag', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'project_id')
    op.add_column('step', sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='projectstatus', create_type=False), autoincrement=False, nullable=False))
    op.drop_table('tag_project')
    op.drop_table('media_project')
    # ### end Alembic commands ###
