"""Update media_model

Revision ID: 9c793d0c1ae8
Revises: 69afcacbe02f
Create Date: 2024-07-18 13:52:41.606198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c793d0c1ae8'
down_revision: Union[str, None] = '69afcacbe02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MP4', 'HLS', name='mediatype').create(op.get_bind())
    op.add_column('media', sa.Column('type', postgresql.ENUM('MP4', 'HLS', name='mediatype', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'type')
    sa.Enum('MP4', 'HLS', name='mediatype').drop(op.get_bind())
    # ### end Alembic commands ###
