"""update is_verifiable

Revision ID: 0c8ecf36ce02
Revises: 8c48ae97fb2b
Create Date: 2026-04-28 14:59:00.483434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ecf36ce02'
down_revision: Union[str, None] = '8c48ae97fb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
