"""add missing columns to user and create role

Revision ID: 109d06e40f9b
Revises: 9b1604aebdf4
Create Date: 2026-06-29 15:07:19.048093

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109d06e40f9b'
down_revision: Union[str, None] = '9b1604aebdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # =====================================================
    # 1. ROLE TABLE
    # =====================================================
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_role_name'),
        'role',
        ['name'],
        unique=True
    )

    # =====================================================
    # 2. SAFE ADDITIONS TO USER TABLE
    # =====================================================

    op.add_column(
        'user',
        sa.Column('firstname', sa.String(length=255), nullable=True)
    )

    op.add_column(
        'user',
        sa.Column('lastname', sa.String(length=255), nullable=True)
    )

    op.add_column(
        'user',
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True)
    )

    # =====================================================
    # 3. FIX created_at NULL VALUES
    # =====================================================
    op.execute("""
        UPDATE "user"
        SET created_at = NOW()
        WHERE created_at IS NULL
    """)

    op.alter_column(
        'user',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )

    # =====================================================
    # 4. FIX updated_at NULL VALUES
    # =====================================================
    op.execute("""
        UPDATE "user"
        SET updated_at = NOW()
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'user',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )

    # =====================================================
    # 5. ADD is_active SAFELY
    # =====================================================
    op.add_column(
        'user',
        sa.Column('is_active', sa.Boolean(), nullable=True)
    )

    op.execute("""
        UPDATE "user"
        SET is_active = TRUE
        WHERE is_active IS NULL
    """)

    op.alter_column(
        'user',
        'is_active',
        nullable=False,
        server_default=sa.true()
    )

    op.alter_column(
        'user',
        'is_active',
        server_default=None
    )

    # =====================================================
    # 6. USER_ROLE TABLE
    # =====================================================
    op.create_table(
        'user_role',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_email', sa.String(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('assigned_by', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id']),
        sa.ForeignKeyConstraint(['user_email'], ['user.email']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_email', 'role_id', name='uq_user_role')
    )

    op.create_index(
        op.f('ix_user_role_role_id'),
        'user_role',
        ['role_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_user_role_user_email'),
        'user_role',
        ['user_email'],
        unique=False
    )
    op.drop_column('user', 'role')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_index(op.f('ix_user_role_user_email'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
