"""add mp3 to mediatype

Revision ID: 1b05542169d7
Revises: ff8531164a4c
Create Date: 2026-03-06 11:31:02.590076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '1b05542169d7'
down_revision: Union[str, None] = 'ff8531164a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS', 'MP3'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
