"""Add step and task changes

Revision ID: 1e99de4ea023
Revises: 3fc14e44e2a9
Create Date: 2025-03-28 16:36:01.746683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '1e99de4ea023'
down_revision: Union[str, None] = '3fc14e44e2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('redundancy_rate', sa.Float(), nullable=False))
    op.add_column('step', sa.Column('completeness_rate', sa.Float(), nullable=False))
    op.add_column('step', sa.Column('allow_empty_annotation', sa.Boolean(), nullable=False))
    op.add_column('step', sa.Column('max_tasks_per_person', sa.Integer(), nullable=False))
    op.alter_column('step', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('task', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('redundancy', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=False))
    op.sync_enum_values('public', 'annotationstatus', ['DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE'],
                        [TableReference(table_schema='public', table_name='annotation', column_name='annotation_status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'stepstatus', ['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
                        [TableReference(table_schema='public', table_name='step', column_name='status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'taskstatus', ['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
                        [TableReference(table_schema='public', table_name='task', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'taskstatus', ['DRAFT', 'PENDING', 'ENDED'],
                        [TableReference(table_schema='public', table_name='task', column_name='status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'stepstatus', ['DRAFT', 'PENDING', 'ENDED'],
                        [TableReference(table_schema='public', table_name='step', column_name='status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'annotationstatus', ['DRAFT', 'PENDING', 'ENDED'],
                        [TableReference(table_schema='public', table_name='annotation', column_name='annotation_status')],
                        enum_values_to_rename=[])
    op.drop_column('task', 'priority')
    op.drop_column('task', 'redundancy')
    op.drop_column('task', 'expiration_date')
    op.alter_column('step', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('step', 'max_tasks_per_person')
    op.drop_column('step', 'allow_empty_annotation')
    op.drop_column('step', 'completeness_rate')
    op.drop_column('step', 'redundancy_rate')
    # ### end Alembic commands ###
