"""Update db_model_lint

Revision ID: 23ad5e7952b2
Revises: e6b1ebebb3f9
Create Date: 2024-12-10 15:39:12.430955

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ad5e7952b2'
down_revision: Union[str, None] = 'e6b1ebebb3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('config_data', sa.JSON(), nullable=True))
    op.drop_column('plugin', 'configData')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin',
                  sa.Column('configData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('plugin', 'config_data')
    # ### end Alembic commands ###
