"""Migrate PluginModel to SQLAlchemy v2

Revision ID: 271da1758f48
Revises: a41ce8f71f4f
Create Date: 2026-01-14 11:35:33.335833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '271da1758f48'
down_revision: Union[str, None] = 'a41ce8f71f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plugin', 'data_categories',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plugin', 'type',
               existing_type=postgresql.ENUM('LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', name='typeplugin'),
               nullable=False)
    op.alter_column('plugin', 'display_zone',
               existing_type=postgresql.ENUM('BLOC', 'SPAN_MODAL_LEFT', 'SPAN_MODAL_RIGHT', 'GROUP_MODAL', name='displayzone'),
               nullable=False)
    op.alter_column('plugin', 'step_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plugin', 'config_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'config_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('plugin', 'step_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plugin', 'display_zone',
               existing_type=postgresql.ENUM('BLOC', 'SPAN_MODAL_LEFT', 'SPAN_MODAL_RIGHT', 'GROUP_MODAL', name='displayzone'),
               nullable=True)
    op.alter_column('plugin', 'type',
               existing_type=postgresql.ENUM('LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', name='typeplugin'),
               nullable=True)
    op.alter_column('plugin', 'data_categories',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plugin', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
