"""Add available plugins to plugin

Revision ID: 2bb2fb974427
Revises: a07504c8006d
Create Date: 2025-09-05 12:38:38.275039

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bb2fb974427'
down_revision: Union[str, None] = 'a07504c8006d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('available_plugins', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'available_plugins')
    # ### end Alembic commands ###
