"""Update db_model2

Revision ID: 3729afc7c00b
Revises: 23ad5e7952b2
Create Date: 2025-01-16 14:08:30.028323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3729afc7c00b'
down_revision: Union[str, None] = '23ad5e7952b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').create(op.get_bind())
    sa.Enum('LABEL', 'AUTOCOMPLETE', name='typeplugin').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='stepstatus').create(op.get_bind())
    sa.Enum('SEGMENTATION', 'TRANSCRIPTION', 'SPAN', name='annotationtype').create(op.get_bind())
    sa.Enum('MP4', 'HLS', name='mediatype').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='annotationstatus').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='taskstatus').create(op.get_bind())
    sa.Enum('LDD', 'AMALIA', name='taskdatatype').create(op.get_bind())
    sa.Enum('IN', 'OUT', name='inoutenum').create(op.get_bind())
    sa.Enum('STATIC', 'DYNAMIC', name='distributionmode').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='projectstatus').create(op.get_bind())
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('MP4', 'HLS', name='mediatype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('annotation_status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='annotationstatus', create_type=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='projectstatus', create_type=False), nullable=False),
    sa.Column('distribution_mode', postgresql.ENUM('STATIC', 'DYNAMIC', name='distributionmode', create_type=False), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('empty_annotations', sa.Boolean(), nullable=True),
    sa.Column('allow_skip', sa.Boolean(), nullable=True),
    sa.Column('control_weights', sa.Integer(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_project',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'project_id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('annotation_type', postgresql.ENUM('SEGMENTATION', 'TRANSCRIPTION', 'SPAN', name='annotationtype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='stepstatus', create_type=False), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data_categories', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('LABEL', 'AUTOCOMPLETE', name='typeplugin', create_type=False), nullable=True),
    sa.Column('display_zone', postgresql.ENUM('BLOC', 'COMPONENT', name='displayzone', create_type=False), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("name NOT LIKE '%% %%'", name='check_name_no_spaces'),
    sa.CheckConstraint('name = LOWER(name)', name='check_name_lowercase'),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_project',
    sa.Column('tag_key', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag_key'], ['tag.key'], ),
    sa.PrimaryKeyConstraint('tag_key', 'project_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('data_type', postgresql.ENUM('LDD', 'AMALIA', name='taskdatatype', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='taskstatus', create_type=False), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_task',
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('direction', postgresql.ENUM('IN', 'OUT', name='inoutenum', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_id', 'task_id')
    )
    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_comment')
    op.drop_table('annotation_task')
    op.drop_table('task')
    op.drop_table('tag_project')
    op.drop_table('plugin')
    op.drop_table('tag')
    op.drop_table('step')
    op.drop_table('media_project')
    op.drop_table('project')
    op.drop_table('annotation')
    op.drop_table('user')
    op.drop_table('media')
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='projectstatus').drop(op.get_bind())
    sa.Enum('STATIC', 'DYNAMIC', name='distributionmode').drop(op.get_bind())
    sa.Enum('IN', 'OUT', name='inoutenum').drop(op.get_bind())
    sa.Enum('LDD', 'AMALIA', name='taskdatatype').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='taskstatus').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='annotationstatus').drop(op.get_bind())
    sa.Enum('MP4', 'HLS', name='mediatype').drop(op.get_bind())
    sa.Enum('SEGMENTATION', 'TRANSCRIPTION', 'SPAN', name='annotationtype').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='stepstatus').drop(op.get_bind())
    sa.Enum('LABEL', 'AUTOCOMPLETE', name='typeplugin').drop(op.get_bind())
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').drop(op.get_bind())
    # ### end Alembic commands ###
