"""Update db_model2

Revision ID: 3729afc7c00b
Revises: 23ad5e7952b2
Create Date: 2025-01-16 14:08:30.028323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3729afc7c00b'
down_revision: Union[str, None] = '23ad5e7952b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.email'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('taskComment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskComment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"taskComment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='taskComment_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='taskComment_pkey')
    )
    op.drop_table('task_comment')
    # ### end Alembic commands ###
 ###
