"""Add display_zone

Revision ID: 3e6bf3810879
Revises: 1b05542169d7
Create Date: 2026-04-09 14:55:30.397798

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '3e6bf3810879'
down_revision: Union[str, None] = '1b05542169d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='displayzone',
        new_values=['BLOC', 'SPAN_MODAL_LEFT', 'SPAN_MODAL_LEFT_SEGMENT', 'SPAN_MODAL_RIGHT', 'GROUP_MODAL'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='displayzone',
        new_values=['BLOC', 'SPAN_MODAL_LEFT', 'SPAN_MODAL_RIGHT', 'GROUP_MODAL'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS', 'MP3'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
