"""Update db_model with json column

Revision ID: 3fc14e44e2a9
Revises: 3729afc7c00b
Create Date: 2025-01-27 10:13:21.985542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fc14e44e2a9'
down_revision: Union[str, None] = '3729afc7c00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('player_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('media', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('task', sa.Column('documentation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'documentation')
    op.drop_column('media', 'details')
    op.drop_column('media', 'player_parameters')
    # ### end Alembic commands ###
