"""add Span step

Revision ID: 5590e737eb7f
Revises: d9445fb3c37b
Create Date: 2024-10-07 14:29:18.726342

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '5590e737eb7f'
down_revision: Union[str, None] = 'd9445fb3c37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_task_id_fkey', 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'task_id')
    op.drop_constraint('annotation_task_annotation_id_fkey', 'annotation_task', type_='foreignkey')
    op.drop_constraint('annotation_task_task_id_fkey', 'annotation_task', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_task', 'task', ['task_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'annotation_task', 'annotation', ['annotation_id'], ['id'], onupdate='CASCADE',
                          ondelete='CASCADE')
    op.sync_enum_values('public', 'annotationtype', ['SEGMENTATION', 'TRANSCRIPTION', 'SPAN'],
                        [TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'annotationtype', ['SEGMENTATION', 'TRANSCRIPTION'],
                        [TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
                        enum_values_to_rename=[])
    op.drop_constraint(None, 'annotation_task', type_='foreignkey')
    op.drop_constraint(None, 'annotation_task', type_='foreignkey')
    op.create_foreign_key('annotation_task_task_id_fkey', 'annotation_task', 'task', ['task_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key('annotation_task_annotation_id_fkey', 'annotation_task', 'annotation', ['annotation_id'],
                          ['id'], ondelete='CASCADE')
    op.add_column('annotation', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('annotation_task_id_fkey', 'annotation', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
