"""update is_ required to plugin config

Revision ID: 5940cdd6d66d
Revises: b89923095c8d
Create Date: 2026-07-17 15:04:42.609655

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5940cdd6d66d'
down_revision: Union[str, None] = 'b89923095c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
