"""add auto-summary annotation_type

Revision ID: 64f3bcd242c8
Revises: 1e99de4ea023
Create Date: 2025-04-02 12:41:06.640807

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '64f3bcd242c8'
down_revision: Union[str, None] = '1e99de4ea023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'annotationtype', ['SEGMENTATION', 'TRANSCRIPTION', 'SPAN', 'AUTO_SUMMARY'],
                        [TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'annotationtype', ['SEGMENTATION', 'TRANSCRIPTION', 'SPAN'],
                        [TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
