"""change enum status project

Revision ID: 668e097dd85f
Revises: e6ba6c284b83
Create Date: 2025-05-12 09:17:59.346230

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '668e097dd85f'
down_revision: Union[str, None] = 'e6ba6c284b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'projectstatus', ['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'ENDED', 'DONE'],
                        [TableReference(table_schema='public', table_name='project', column_name='status')],
                        enum_values_to_rename=[])
    op.execute("UPDATE project SET status = 'DONE' WHERE status = 'ENDED'")
    op.sync_enum_values(
        'public',
        'projectstatus',
        ['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
        [TableReference(table_schema='public', table_name='project', column_name='status')]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'projectstatus', ['DRAFT', 'PENDING', 'ENDED'],
                        [TableReference(table_schema='public', table_name='project', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
