"""Add updated_by and updated_at into project

Revision ID: 6752eb34f10e
Revises: 9b1604aebdf4
Create Date: 2026-06-12 16:11:51.812662

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6752eb34f10e'
down_revision: Union[str, None] = '9b1604aebdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'updated_by')
    # ### end Alembic commands ###
