"""add editable to plugin

Revision ID: 771183ab9b2d
Revises: 81eaf5cc7d13
Create Date: 2026-01-07 14:59:42.858307

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '771183ab9b2d'
down_revision: Union[str, None] = '81eaf5cc7d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
