"""Add archived status into project, step, task and annotation

Revision ID: 81eaf5cc7d13
Revises: 2bb2fb974427
Create Date: 2025-10-14 11:47:58.491226

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81eaf5cc7d13'
down_revision: Union[str, None] = '2bb2fb974427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('archived_status', postgresql.ENUM('DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED', name='annotationstatus', create_type=False), nullable=True))
    op.add_column('project', sa.Column('archived_status', postgresql.ENUM('DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED', name='projectstatus', create_type=False), nullable=True))
    op.add_column('step', sa.Column('archived_status', postgresql.ENUM('DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED', name='stepstatus', create_type=False), nullable=True))
    op.add_column('task', sa.Column('archived_status', postgresql.ENUM('DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED', name='taskstatus', create_type=False), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='annotationstatus',
        new_values=['DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='annotation', column_name='annotation_status'), TableReference(table_schema='public', table_name='annotation', column_name='archived_status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='projectstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='project', column_name='archived_status'), TableReference(table_schema='public', table_name='project', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='stepstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='step', column_name='archived_status'), TableReference(table_schema='public', table_name='step', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='archived_status'), TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='archived_status'), TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='stepstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='step', column_name='archived_status'), TableReference(table_schema='public', table_name='step', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='projectstatus',
        new_values=['DRAFT', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='project', column_name='archived_status'), TableReference(table_schema='public', table_name='project', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='annotationstatus',
        new_values=['DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='annotation', column_name='annotation_status'), TableReference(table_schema='public', table_name='annotation', column_name='archived_status')],
        enum_values_to_rename=[],
    )
    op.drop_column('task', 'archived_status')
    op.drop_column('step', 'archived_status')
    op.drop_column('project', 'archived_status')
    op.drop_column('annotation', 'archived_status')
    # ### end Alembic commands ###
