"""Adjust enum

Revision ID: 826ce4eb16c3
Revises: bb32f136f35b
Create Date: 2025-07-31 11:33:50.977098

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '826ce4eb16c3'
down_revision: Union[str, None] = 'bb32f136f35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'displayzone', ['BLOC', 'SPAN_MODAL_LEFT', 'SPAN_MODAL_RIGHT', 'GROUP_MODAL'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'displayzone', ['BLOC', 'MODAL_LEFT', 'MODAL_RIGHT'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
