"""09/12

Revision ID: 8c99ae53adcf
Revises: 7e93962fde88
Create Date: 2024-12-09 14:52:56.090193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c99ae53adcf'
down_revision: Union[str, None] = '7e93962fde88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').create(op.get_bind())
    op.add_column('plugin', sa.Column('data_categories', sa.String(), nullable=True))
    op.add_column('plugin', sa.Column('display_zone', postgresql.ENUM('BLOC', 'COMPONENT', name='displayzone', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'display_zone')
    op.drop_column('plugin', 'data_categories')
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').drop(op.get_bind())
    # ### end Alembic commands ###
