"""Add new annotation_type for STREAMedia

Revision ID: 909cbfdf5e93
Revises: ff8531164a4c
Create Date: 2026-03-02 11:29:38.147661

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '909cbfdf5e93'
down_revision: Union[str, None] = '1b05542169d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='annotationtype',
        new_values=['SEGMENTATION', 'TRANSCRIPTION', 'SPAN', 'AUTO_SUMMARY', 'VIDEO_SEGMENTATION'],
        affected_columns=[TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='annotationtype',
        new_values=['SEGMENTATION', 'TRANSCRIPTION', 'SPAN', 'AUTO_SUMMARY'],
        affected_columns=[TableReference(table_schema='public', table_name='step', column_name='annotation_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
