"""add new plugin type

Revision ID: 97d6d15ffb83
Revises: e8611a2edded
Create Date: 2026-04-24 14:41:53.082550

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '97d6d15ffb83'
down_revision: Union[str, None] = 'e8611a2edded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', 'ENTITY_LIST_INPUT', 'MULTISELECT_OPTIONS'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', 'ENTITY_LIST_INPUT'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
