"""update status ennum

Revision ID: 9b1604aebdf4
Revises: 0c8ecf36ce02
Create Date: 2026-05-06 11:23:39.018701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '9b1604aebdf4'
down_revision: Union[str, None] = '0c8ecf36ce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED', 'VERIFIED'],
        affected_columns=[TableReference(table_schema='public', table_name='annotation', column_name='annotation_status'), TableReference(table_schema='public', table_name='annotation', column_name='previous_status'), TableReference(table_schema='public', table_name='project', column_name='previous_status'), TableReference(table_schema='public', table_name='project', column_name='status'), TableReference(table_schema='public', table_name='step', column_name='previous_status'), TableReference(table_schema='public', table_name='step', column_name='status', existing_server_default="'DRAFT'::status"), TableReference(table_schema='public', table_name='task', column_name='previous_status'), TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='annotation', column_name='annotation_status'), TableReference(table_schema='public', table_name='annotation', column_name='previous_status'), TableReference(table_schema='public', table_name='project', column_name='previous_status'), TableReference(table_schema='public', table_name='project', column_name='status'), TableReference(table_schema='public', table_name='step', column_name='previous_status'), TableReference(table_schema='public', table_name='step', column_name='status', existing_server_default="'DRAFT'::status"), TableReference(table_schema='public', table_name='task', column_name='previous_status'), TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
