"""add wikidata to plugin types

Revision ID: a07504c8006d
Revises: 826ce4eb16c3
Create Date: 2025-08-13 14:40:31.273639

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a07504c8006d'
down_revision: Union[str, None] = '826ce4eb16c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
