"""Migrate AnnotationTaskModel to SQLAlchemy v2

Revision ID: a41ce8f71f4f
Revises: fcd5cf95d1f0
Create Date: 2026-01-14 11:14:52.264737

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a41ce8f71f4f'
down_revision: Union[str, None] = 'fcd5cf95d1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation', 'annotation_status',
               existing_type=postgresql.ENUM('DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED', name='status'),
               nullable=False)
    op.alter_column('annotation', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('annotation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_annotation_user_email'), table_name='annotation')
    op.drop_index(op.f('idx_annotation_task_id'), table_name='annotation_task')
    op.drop_index(op.f('idx_step_project_id'), table_name='step')
    op.drop_index(op.f('idx_task_expiration_date'), table_name='task', postgresql_where='(expiration_date IS NOT NULL)')
    op.drop_index(op.f('idx_task_status'), table_name='task')
    op.drop_index(op.f('idx_task_step_id'), table_name='task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_step_id'), 'task', ['step_id'], unique=False)
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_expiration_date'), 'task', ['expiration_date'], unique=False, postgresql_where='(expiration_date IS NOT NULL)')
    op.create_index(op.f('idx_step_project_id'), 'step', ['project_id'], unique=False)
    op.create_index(op.f('idx_annotation_task_id'), 'annotation_task', ['task_id'], unique=False)
    op.create_index(op.f('idx_annotation_user_email'), 'annotation', ['user_email'], unique=False)
    op.alter_column('annotation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('annotation', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('annotation', 'annotation_status',
               existing_type=postgresql.ENUM('DRAFT', 'IN_PROGRESS', 'PENDING', 'SKIPPED', 'DONE', 'ARCHIVED', name='status'),
               nullable=True)
    # ### end Alembic commands ###
