"""add typed step settings models with default values

Revision ID: b3bc57fab2ab
Revises: de39ec6298ae
Create Date: 2026-07-28 15:53:10.481628

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3bc57fab2ab'
down_revision: Union[str, None] = 'de39ec6298ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'settings')
    # ### end Alembic commands ###
