"""Adjust‎_embedded_plugin

Revision ID: bb32f136f35b
Revises: 668e097dd85f
Create Date: 2025-07-24 08:23:35.065744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'bb32f136f35b'
down_revision: Union[str, None] = '668e097dd85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('display_config', sa.JSON(), nullable=True))
    op.add_column('plugin', sa.Column('enable_search', sa.Boolean(), nullable=True))
    op.add_column('plugin', sa.Column('data_property', sa.String(), nullable=True))
    op.add_column('plugin', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plugin', 'plugin', ['parent_id'], ['id'])
    op.sync_enum_values('public', 'typeplugin', ['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'displayzone', ['BLOC', 'MODAL_LEFT', 'MODAL_RIGHT'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'displayzone', ['BLOC', 'COMPONENT'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='display_zone')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'typeplugin', ['LABEL', 'AUTOCOMPLETE'],
                        [TableReference(table_schema='public', table_name='plugin', column_name='type')],
                        enum_values_to_rename=[])
    op.drop_constraint(None, 'plugin', type_='foreignkey')
    op.drop_column('plugin', 'parent_id')
    op.drop_column('plugin', 'data_property')
    op.drop_column('plugin', 'enable_search')
    op.drop_column('plugin', 'display_config')
    # ### end Alembic commands ###
