"""Update db_model

Revision ID: be50ab73e53e
Revises: 5870d3957f89
Create Date: 2024-07-08 13:07:28.141628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be50ab73e53e'
down_revision: Union[str, None] = '5870d3957f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='annotationstatus').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='taskstatus').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='stepstatus').create(op.get_bind())
    sa.Enum('LDD', 'AMALIA', name='taskdatatype').create(op.get_bind())
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='stepstatus', create_type=False), nullable=False),
    sa.Column('annotation_type', postgresql.ENUM('SEGMENTATION', 'TRANSCRIPTION', name='annotationtype', create_type=False), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskComment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('annotation', sa.Column('annotation_status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='annotationstatus', create_type=False), nullable=True))
    op.add_column('annotation', sa.Column('version', sa.Integer(), nullable=True))
    # op.alter_column('annotation', 'result',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=sa.String(),
    #            existing_nullable=True)
    op.drop_constraint('annotation_project_id_fkey', 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'status')
    op.drop_column('annotation', 'project_id')
    op.add_column('task', sa.Column('data_type', postgresql.ENUM('LDD', 'AMALIA', name='taskdatatype', create_type=False), nullable=True))
    op.add_column('task', sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='taskstatus', create_type=False), nullable=True))
    op.add_column('task', sa.Column('lead_time', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('step_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('media_id', sa.Integer(), nullable=True))
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # op.alter_column('task', 'data',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=sa.String(),
    #            existing_nullable=True)
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'step', ['step_id'], ['id'])
    op.create_foreign_key(None, 'task', 'media', ['media_id'], ['id'])
    op.drop_column('task', 'project_id')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.add_column('task', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    op.alter_column('task', 'data',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task', 'media_id')
    op.drop_column('task', 'step_id')
    op.drop_column('task', 'lead_time')
    op.drop_column('task', 'status')
    op.drop_column('task', 'data_type')
    op.add_column('annotation', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('annotation', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'in progress'::text"), autoincrement=False, nullable=True))
    op.create_foreign_key('annotation_project_id_fkey', 'annotation', 'project', ['project_id'], ['id'])
    op.alter_column('annotation', 'result',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('annotation', 'version')
    op.drop_column('annotation', 'annotation_status')
    op.drop_table('taskComment')
    op.drop_table('step')
    op.drop_table('tag')
    op.drop_table('media')
    sa.Enum('LDD', 'AMALIA', name='taskdatatype').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='taskstatus').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='annotationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
