"""25/07 update

Revision ID: d9445fb3c37b
Revises: 9c793d0c1ae8
Create Date: 2024-07-29 13:38:35.692632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9445fb3c37b'
down_revision: Union[str, None] = '9c793d0c1ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('IN', 'OUT', name='inoutenum').create(op.get_bind())
    sa.Enum('STATIC', 'DYNAMIC', name='distributionmode').create(op.get_bind())
    op.create_table('annotation_task',
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('direction', postgresql.ENUM('IN', 'OUT', name='inoutenum', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('annotation_id', 'task_id')
    )
    op.add_column('project', sa.Column('distribution_mode', postgresql.ENUM('STATIC', 'DYNAMIC', name='distributionmode', create_type=False), nullable=True))
    op.add_column('step', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('task', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('step', 'order')
    op.drop_column('project', 'distribution_mode')
    op.drop_table('annotation_task')
    sa.Enum('STATIC', 'DYNAMIC', name='distributionmode').drop(op.get_bind())
    sa.Enum('IN', 'OUT', name='inoutenum').drop(op.get_bind())
    # ### end Alembic commands ###
