"""Add Project model changes

Revision ID: d9a0eace8672
Revises: 709cf4c7ea01
Create Date: 2024-06-11 14:48:52.619262

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9a0eace8672'
down_revision: Union[str, None] = '709cf4c7ea01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SEGMENTATION', 'TRANSCRIPTION', name='annotationtype').create(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='projectstatus').create(op.get_bind())
    op.drop_table('user_task')
    op.alter_column('annotation', 'status',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True,
                    existing_server_default=sa.text("'in progress'::text"))
    op.add_column('project', sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ENDED', name='projectstatus',
                                                                 create_type=False), nullable=False))
    op.add_column('project', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('empty_annotations', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('allow_skip', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('control_weights', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.alter_column('project', 'title',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    nullable=False)
    op.alter_column('project', 'description',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('task', 'name',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('task', 'instruction',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('user', 'email',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('user', 'role',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('user', 'email',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('task', 'instruction',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('task', 'name',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('project', 'description',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('project', 'title',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    nullable=True)
    op.drop_column('project', 'pinned_at')
    op.drop_column('project', 'control_weights')
    op.drop_column('project', 'allow_skip')
    op.drop_column('project', 'empty_annotations')
    op.drop_column('project', 'is_published')
    op.drop_column('project', 'annotation_type')
    op.drop_column('project', 'status')
    op.alter_column('annotation', 'status',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True,
                    existing_server_default=sa.text("'in progress'::text"))
    op.create_table('user_task',
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('task_status', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('attributed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.Column('validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='user_task_task_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_task_user_id_fkey'),
                    sa.PrimaryKeyConstraint('user_id', name='user_task_pkey')
                    )
    sa.Enum('DRAFT', 'PENDING', 'ENDED', name='projectstatus').drop(op.get_bind())
    # ### end Alembic commands ###
