"""New timeline plugin

Revision ID: de39ec6298ae
Revises: 6752eb34f10e
Create Date: 2026-07-10 17:06:12.771107

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'de39ec6298ae'
down_revision: Union[str, None] = '6752eb34f10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', 'ENTITY_LIST_INPUT', 'MULTISELECT_OPTIONS', 'TIMELINE_ROW'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', 'ENTITY_LIST_INPUT', 'MULTISELECT_OPTIONS'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
