"""Update db_mode plugin

Revision ID: e6b1ebebb3f9
Revises: 5590e737eb7f
Create Date: 2024-12-10 08:33:09.977622

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6b1ebebb3f9'
down_revision: Union[str, None] = '5590e737eb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').create(op.get_bind())
    sa.Enum('LABEL', 'AUTOCOMPLETE', name='typeplugin').create(op.get_bind())
    op.create_table('plugin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('data_categories', sa.String(), nullable=True),
                    sa.Column('type', postgresql.ENUM('LABEL', 'AUTOCOMPLETE', name='typeplugin', create_type=False),
                              nullable=True),
                    sa.Column('display_zone',
                              postgresql.ENUM('BLOC', 'COMPONENT', name='displayzone', create_type=False),
                              nullable=True),
                    sa.Column('step_id', sa.Integer(), nullable=True),
                    sa.Column('configData', sa.JSON(), nullable=True),
                    sa.CheckConstraint("name NOT LIKE '%% %%'", name='check_name_no_spaces'),
                    sa.CheckConstraint('name = LOWER(name)', name='check_name_lowercase'),
                    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin')
    sa.Enum('LABEL', 'AUTOCOMPLETE', name='typeplugin').drop(op.get_bind())
    sa.Enum('BLOC', 'COMPONENT', name='displayzone').drop(op.get_bind())
    # ### end Alembic commands ###
