"""modify redundancy and completion_rate

Revision ID: e6ba6c284b83
Revises: 64f3bcd242c8
Create Date: 2025-04-03 14:43:25.889049

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6ba6c284b83'
down_revision: Union[str, None] = '64f3bcd242c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('redundancy', sa.Integer(), nullable=True))
    op.execute("UPDATE step SET redundancy = 1 WHERE redundancy IS NULL")
    op.alter_column('step','redundancy', nullable= False)
    
    op.drop_column('step', 'redundancy_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('redundancy_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('step', 'redundancy')
    # ### end Alembic commands ###
