"""add entityLabelInput to enums

Revision ID: e8611a2edded
Revises: 8aede2e681f5
Create Date: 2026-04-20 17:50:39.340990

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e8611a2edded'
down_revision: Union[str, None] = '8aede2e681f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS', 'MP3'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL', 'ENTITY_LIST_INPUT'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='typeplugin',
        new_values=['LABEL', 'AUTOCOMPLETE', 'LIST_ITEMS', 'SUGGESTION_LIST', 'INPUT_LABEL'],
        affected_columns=[TableReference(table_schema='public', table_name='plugin', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='mediatype',
        new_values=['MP4', 'HLS'],
        affected_columns=[TableReference(table_schema='public', table_name='media', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
