"""Add skipped_by to annotation

Revision ID: ff8531164a4c
Revises: 31a101b4ea0b
Create Date: 2026-02-09 12:14:05.997934

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff8531164a4c'
down_revision: Union[str, None] = '31a101b4ea0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('skipped_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'skipped_by')
    # ### end Alembic commands ###
