events { worker_connections 1024; }

http {
	server {
		listen       80;
		listen  [::]:80;
		server_name  localhost;
		index index.html index.htm;


		location / {
			root   /usr/share/nginx/html;
			index  index.html;
			autoindex on;
			try_files $uri $uri/ /index.html?$query_string /index.html;
			include mime.types;
			types {
				application/javascript js mjs;
			}
		}
		error_page	404 /404.html;
    
	}
}
