# This configuration is intended for development purpose,
# it's **your** responsibility to harden it for production
name: ground-control-services
services:
  postgresql:
    image: postgres:17.4
    container_name: ground-control-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ground_control_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
