default:
  player_expert:
    base_url: "https://player-expert.p.sas.ina/notilusLdd/notilus/search/plugin"
    verify_tls: false
  keycloak:
    url: "http://keycloak:9080/"
    realm: "ground-control"
    client_id: "backend"
    client_secret: "S95Ja09NGqzB4UvXoUgbcM39IdTz8826"
