### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###


### cR2
POST http://localhost:8000/plugin/
accept: application/json
Content-Type: application/json

{
  "name": "name_test",
  "type": "label",
  "data_categories": "string",
  "display_zone": "bloc",
  "step_id": 1,
  "config_data": {
                "type": "plugin_autocompelete",
                "data_type":"json",
                "data_source": "https://player-expert.d.sas.ina/assets/listOfChannel/tvChannels.json",
                "search_attr": "title",
                "search_query_param": "q",
                "search_item_sort": "title,asc",
                "response_id_key": "id",
                "response_ext_id_key": "ext_id",
                "response_label_key": "label"
            }
}

###

GET http://localhost:8000/plugins/step/1/plugin_autocompelete/display/bloc

###
GET http://localhost:8000/plugin/13/search

###
# curl -X 'GET'
#  'http://localhost:8000/plugins/13/search?query=SS'
#  -H 'accept: application/json'
GET http://localhost:8000/plugins/18/search?query=SS
accept: application/json

###

